name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Restore local.properties
        run: |
          echo "API_NINJAS_API_URL=${{secrets.API_NINJAS_API_URL}}" >> //home//runner//work//DanielNolasco//DanielNolasco//local.properties
          echo "API_NINJAS_X_API_KEY=${{secrets.API_NINJAS_X_API_KEY}}" >> //home//runner//work//DanielNolasco//DanielNolasco//local.properties
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Unit tests
        run: ./gradlew testDebugUnitTest

      - name: Detekt validation
        run: ./gradlew detekt
